name = "DispatchDoctor"
uuid = "8d63f2c5-f18a-4cf2-ba9d-b3f60fc568c8"
authors = ["MilesCranmer <miles.cranmer@gmail.com> and contributors"]
version = "0.4.3"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
MacroTools = "0.5"
Preferences = "1"
TestItems = "0.1"
julia = "1.6.7"
